Revert "build-llvm.py: Fix PGO using LLVM as training data without '--full-toolchain'"
Temporary fix for:

Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/./build-llvm.py", line 617, in <module>
    llvm_builder.tools.clang_tblgen = Path(bootstrap.folders.build, 'bin/clang-tblgen')
NameError: name 'bootstrap' is not defined. Did you mean: 'use_bootstrap'?

This reverts commit 17103fcfce954da45d1325c40cb590442efe3e29.

Change-Id: Ib845e5ae213b3e18650c19c2c16dbc1affa838dd