Revert "tc_scripts: drop x86 support"
It seems we could not drop it now.
Run Build Command(s):/usr/bin/ninja cmTC_671f0 && [1/2] Building C object CMakeFiles/cmTC_671f0.dir/testCCompiler.c.o
FAILED: CMakeFiles/cmTC_671f0.dir/testCCompiler.c.o
/build/llvm/instrumented/bin/clang   -O3 -o CMakeFiles/cmTC_671f0.dir/testCCompiler.c.o -c /build/llvm/profiling/CMakeFiles/CMakeTmp/testCCompiler.c
error: unable to create target: 'No available targets are compatible with triple "x86_64-pc-linux-gnu"'
1 error generated.
ninja: build stopped: subcommand failed.

This reverts commit 41325f5cacd11757600097fbf2eca34ab8a3f375.

Change-Id: Ib10fe25e56a545736eafc013ff6c80a72f0a9cd4